{
    'name': 'Community Module',
    'version': '1.0',
    'summary': 'Manage communities in Odoo',
    'description': 'A simple module to manage communities in Odoo backend.',
    'category': 'Tools',
    'license': 'LGPL-3',
    'author': 'Rizwan',
    'depends': ['base', 'sale', 'product', 'module_sb', 'crm'],
    'data': [
        'security/ir.model.access.csv',
        'security/security.xml',
        'data/heartbeat_groups.xml',
        'views/community.xml',
        'views/templates.xml',
        'views/community_product_inherited.xml',
        'views/community_homeplans.xml',
        'views/amenities_categories.xml',
        'views/amenities.xml',
        'views/web_form_data.xml',
        'views/crm_lead.xml',
        'views/lot.xml',
        'views/section.xml',
    ],
    'installable': True,
    'auto_install': False,
    'application': True,
}
